lexik_translation:
    fallback_locale: [ en ]                             # (required) default locale(s) to use
    managed_locales: [ en, fr, ar, de, es, pl, pt, it ] # (required) locales that the bundle has to manage
    # auto_cache_clean: true                            # Automatically clear translations cache files

services:
    Abenmada\TranslationPlugin\DataGrid\DataGridFormatter:
        arguments:
            $localeManager: '@Lexik\Bundle\TranslationBundle\Manager\LocaleManagerInterface'
            $storage: '%lexik_translation.storage.type%'

    Abenmada\TranslationPlugin\DataGrid\DataGridRequestHandler:
        arguments:
            $channelTranslationRepository: '@abenmada_translation_plugin.repository.channel_translation'
            $channelTranslationFactory: '@abenmada_translation_plugin.factory.channel_translation'
            $channelTranslationManager: '@abenmada_translation_plugin.manager.channel_translation'
            $transUnitManager: '@lexik_translation.trans_unit.manager'
            $fileManager: '@lexik_translation.file.manager'
            $storage: '@lexik_translation.translation_storage'
            $localeManager: '@Lexik\Bundle\TranslationBundle\Manager\LocaleManagerInterface'

    Lexik\Bundle\TranslationBundle\Translation\Loader:
        class: Abenmada\TranslationPlugin\Loader\DatabaseLoader
        arguments:
            $channelTranslationRepository: '@abenmada_translation_plugin.repository.channel_translation'
            $storage: '@lexik_translation.translation_storage'
        tags:
            - { name: 'translation.loader', alias: 'database' }
